name: Lint

on: pull_request_target

jobs:
  lint:  # Runs linting package checks for code styling.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black==19.10b0 isort
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 climpred
      - name: Lint with black
        shell: bash -l {0}
        run: |
          black --check climpred
      - name: Lint with isort
        shell: bash -l {0}
        run: |
          isort --check-only climpred
